### PR TITLE
add glyph

### PR DESCRIPTION
**Pull request by theavege**
# Description

This is a simple example for [33](https://github.com/fltk-rs/demos/pull/33).

### CODE REVIEW

**Comment by MoAlyousef** [comment]
I'm not sure what's supposed to happen!
Please minimize the example and explain what's happening vs what's expected to happen

**Comment by theavege** [comment]
This is the smallest example I could come up with. You need to select an element from the left side, it should appear on the right side.

**Comment by theavege** [comment]
@MoAlyousef Do you have any comments about MR? Will you accept?

**Comment by theavege** [comment]
What's wrong?

**Comment by MoAlyousef** [comment]
Isn’t this just code to demonstrate a problem?

**Comment by theavege** [comment]
I thought you would either deny the problem or accept it when it was fixed in parent's project.

**Comment by MoAlyousef** [comment]
I can’t debug a program with no minimal repro. From a cursory look it seems to be a logical error in the code.

**Pull request closed without merging**
