### PR TITLE
Added taskbar visibility for example shapedwindow.rs

### PR DESCRIPTION
**Pull request by SigmaEG**
Refactored version of the original shapedwindow.rs example code, this version shows your application within the taskbar (as a workaround, not as an official method however it works fairly well).

* Also works with .set_border(false) if you don't want a ShapedWindow but want a rectangular borderless window instead
- Sigma

# Description

Does not fix a "bug" per say however a regular ShapedWindow/Borderless window does not appear in the taskbar, this allows a workaround for your application to be shown in the taskbar and still function without any issues.

### CODE REVIEW

**Review by SigmaEG — COMMENTED** [review]
Fixed typo

**Comment by SigmaEG** [comment]
image

**Comment by MoAlyousef** [comment]
Thank you for the PR :)

**Comment by SigmaEG** [comment]
> Thank you for the PR :)

Spent quite the amount of time, you have no idea how long, trying to find a solution for this, literally none existed so I created this little workaround that works quite well. :)

**Pull request merged**
